import 'package:get/get.dart';
import 'package:sislab/app/data/profile_response.dart'; // pastikan path benar
import 'package:http/http.dart' as http;
import 'dart:convert';

import 'package:sislab/app/utils/api.dart';

class ProfileController extends GetxController {
  var isLoading = false.obs;
  var user = Rxn<User>();

  final String token =
      "Bearer sxiyZAalOAaU1RUYNmD3prEkymplPzS59WVsxjNed884cce5"; // Ganti token dengan token yang benar

  Future<void> fetchProfile() async {
    isLoading.value = true;

    try {
      final response = await http.get(
        Uri.parse(BaseUrl.profile), // Pastikan BaseUrl.profile valid
        headers: {
          "Accept": "application/json",
          "Authorization": token,
        },
      );

      print('Response status: ${response.statusCode}');
      print('Response body: ${response.body}');

      if (response.statusCode == 200) {
        final data = json.decode(response.body);
        final profile = Autogenerated.fromJson(data);
        user.value = profile.user;
      } else {
        Get.snackbar('Error', 'Gagal mengambil data profil: ${response.statusCode}');
      }
    } catch (e) {
      Get.snackbar('Error', 'Terjadi kesalahan: $e');
    } finally {
      isLoading.value = false;
    }
  }
}
