import 'package:get/get.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:sislab/app/data/peminjaman_response.dart';

class PeminjamanController extends GetxController {
  var isLoading = true.obs;
  var peminjamanList = <Data>[].obs;

  @override
  void onInit() {
    fetchPeminjaman();
    super.onInit();
  }

  void fetchPeminjaman() async {
    try {
      isLoading(true);
      final response = await http.get(Uri.parse('http://127.0.0.1:8000/api/peminjaman'));

      if (response.statusCode == 200) {
        final jsonResponse = json.decode(response.body);
        final dataResponse = Autogenerated.fromJson(jsonResponse);
        peminjamanList.value = dataResponse.data ?? [];
      } else {
        Get.snackbar('Error', 'Gagal mengambil data peminjaman');
      }
    } catch (e) {
      Get.snackbar('Error', 'Terjadi kesalahan: $e');
    } finally {
      isLoading(false);
    }
  }
}
