import 'package:get/get.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:sislab/app/data/barang_response.dart'; // asumsi nama file-nya ini

class BarangController extends GetxController {
  var isLoading = true.obs;
  var barangList = <Data>[].obs;

  @override
  void onInit() {
    fetchBarang();
    super.onInit();
  }

  void fetchBarang() async {
    try {
      isLoading(true);
      final response = await http.get(Uri.parse('http://127.0.0.1:8000/api/barang'));

      if (response.statusCode == 200) {
        final jsonResponse = json.decode(response.body);
        final dataResponse = Autogenerated.fromJson(jsonResponse);
        barangList.value = dataResponse.data ?? [];
      } else {
        Get.snackbar('Error', 'Gagal mengambil data barang');
      }
    } catch (e) {
      Get.snackbar('Error', 'Terjadi kesalahan: $e');
    } finally {
      isLoading(false);
    }
  }
}
